os:
  - linux
  - osx

sudo: false

dist: xenial

addons:
  apt:
    packages:
      - git

git:
  depth: 5

language: cpp
compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update       ; fi

script: ./.travis.sh


